### ISSUE TITLE
Apply to additional investigative data journalism grants

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/pollution_analysis_kurdistan#14]
- [x] https://earthjournalism.net/opportunities/story-grants-on-green-recovery-from-the-covid-19-pandemic (Deadline 10th Jan)
- [x] https://fij.org/apply-for-a-grant/ (Deadline 31st Jan)
- [x] https://pulitzercenter.org/grants-fellowships/opportunities-journalists/data-journalism-grants (deadline 31st Jan)

**Comment by ChristinaLast** [comment]
Application to EJN here: https://docs.google.com/document/d/1lxzoTRMqKeajZ53mdEq1Gro0LDrTBKcT5dLk0Peade0/edit

**Comment by ChristinaLast** [comment]
EJN Template: https://earthjournalism.net/sites/default/files/2021-11/EJN%20Story%20Grant%20Budget%20Template_GBP.xlsx

**Comment by TomBrown4444** [comment]
[EJN Story Grant Budget Template_GBP Pollution Project.xlsx](https://github.com/ChristinaLast/pollution_analysis_kurdistan/files/7833775/EJN.Story.Grant.Budget.Template_GBP.Pollution.Project.xlsx)
