### ISSUE TITLE
Get Iraqi Kurdistan visas (plus extras)

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#16]
- [x] Fill out Iraqi embassy form, using the journalist one: https://www.mofa.gov.iq/london/en/visa/
- [x] Schedule embassy appointment
- [x] Book a PCR test in advance
- [x] Book with a taxi company to pick you up in advance of arriving in Erbil airport
- [x] follow instructions provided by https://againstthecompass.com/en/iraqi-kurdistan-travel-guide/

**Comment by TomBrown4444** [comment]
@ChristinaLast  to investigte current status of travelling to USA after Kurdistani Iraq on J1 Visa

**Comment by ChristinaLast** [comment]
@ChristinaLast to book PCR test at DAM Fulham

**Comment by ChristinaLast** [comment]
@ChristinaLast to collect additional $400 from 113 Kensington High Street, Kensington And Chelsea, Greater London, England TUE 22nd MAR 2022
