### ISSUE TITLE
Make doctor's appointment to check for vaccinations

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#19]
Check for vaccinations

**Comment by ChristinaLast** [comment]
Hey! @Alannah Travers ♥️😷 did you get any vaccinations before going to Iraq? aside from the usual, hep a etc?
[21:15, 07/03/2022] Alannah Travers ♥️😷: Lol no
[21:15, 07/03/2022] Alannah Travers ♥️😷: Nothing
