### ISSUE TITLE
@TomBrown4444 to download manually all flaring data from US lab (use Christina login)

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#24]
Christina to provide login

**Comment by ChristinaLast** [comment]
#### VNF Data Login
1. Go to this [website](https://eogdata.mines.edu/products/vnf/#download)
2. If above doesnt work, Google "EOG Mines VNF data" 
3. Navigate to the following 
![Screenshot 2022-02-21 at 06 45 13](https://user-images.githubusercontent.com/36204574/154903394-07c73b2c-6224-471b-b964-61c148b74a1f.png)
![Screenshot 2022-02-21 at 06 45 31](https://user-images.githubusercontent.com/36204574/154903406-42931f87-3cee-4204-926c-9125b89d5de3.png)

3. Search in 1Pass "EOG VNF Login"
4. Use details to login
5. Download [7-zip](https://www.7-zip.org/)
5. Download all `NPP csv` links ![Screenshot 2022-02-21 at 06 43 59](https://user-images.githubusercontent.com/36204574/154903107-8faad40f-b486-452d-9714-56348378f7b4.png)

**Comment by ChristinaLast** [comment]
It would be helpful if you can find some metadata (information about the data like what all the variables mean), and then let me know what you think is useful, Also, I dont know the difference between `NPP` and `J01` atm, it would be good to know what that is.

We found the metadata file, link [here](https://eogdata.mines.edu/products/vnf/vnf_readme_v30_r20211012.xlsx)

**Comment by ChristinaLast** [comment]
- [X] @ChristinaLast downloaded September 2018-today downloaded

**Comment by ChristinaLast** [comment]
Tom to download from 22nd february 2022 to current date.
