### ISSUE TITLE
Get letter of intent from Rudaw/Alannah

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#25]
- [x] Edit [this letter](https://docs.google.com/document/d/1Y7k2SYbwAFjVBCJvUksmPML8BjOkUbn5WC1Uph3OKxc/edit?usp=sharing) to indicate Rudaw will publish and switch GRID-Arendal name for ERC.
- [x] Add Allanah's signature
- [x] Add rudaw logo
- [x] Send to ERC along with additional letter for them to sign

**Comment by ChristinaLast** [comment]
Link to Letter of intent from Alannah [here](https://docs.google.com/document/d/1Y7k2SYbwAFjVBCJvUksmPML8BjOkUbn5WC1Uph3OKxc/edit?usp=sharing)
