### ISSUE TITLE
Clean Iraq pollution data

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/pollution_analysis_kurdistan#3]
Filter data imported from excel to Python using pandas: https://colab.research.google.com/drive/1kMjQgDKChoFIALaisUXxnQjBn2Ctdqvu?usp=sharing

**Comment by ChristinaLast** [comment]
> Filter data imported from excel to Python using pandas: https://colab.research.google.com/drive/1kMjQgDKChoFIALaisUXxnQjBn2Ctdqvu?usp=sharing

Thanks for the link, i'll comment in here now to help with debugging. Let me know if you get really stuck.

In terms of the desription of this task. Its not clear to me how you plan to filter the data. Are you able to create "tickboxes" that give me a better idea of how you plan to filter the data?

For example:
- [x] Filter out hydroelectric power stations (not polluting) by the`"hydro"` tag
- [x] Remove any non-existent power stations
- [x] ...

**Comment by TomBrown4444** [comment]
Filtered "hydro" out of Iraqi power plant data set and uploaded csv
