### ISSUE TITLE
Research which areas of Kurdistan can be considered Kurdistan and consult with Alannah on this (so you don't annoy Iraq/KRG)

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#43]
- [x] find out the status of kirkuk
- [x] figure out the exact border regions so @ChristinaLast can attribute flaring stations appropriately

**Comment by ChristinaLast** [comment]
Link to administrative regions in kurdistan [here](https://drive.google.com/file/d/1210rcTe9v8rR91BIg0uhSAQqnvmsPhL4/view?usp=sharing)

Source: https://www.arcgis.com/apps/View/index.html?appid=49c80db2bddd4c21b5b59c3e4f8129bf
