### ISSUE TITLE
Get stats of population exposure to PM2.5 (using AOD conversion)

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#51]
- Please take a look at [this data](https://developers.google.com/earth-engine/datasets/catalog/CIESIN_GPWv411_GPW_Population_Density) for population density. I will extract this data for the study region much the same as for other satellite data, but I believe the most recent measure was on 2020, so it will not be in timeseries (i.e. there is only one value per ~900m grid cells.

- I am keen to calculate exposure to AOD above a specific threshold which will give us an idea of total no. of people exposed to air pollution.

**Comment by ChristinaLast** [comment]
When I read this ^^ I was like, oooh thanks such a detailed explanation... then I realised you reposted my comments... 😭

- [x] going to run satellite extraction script for the same regions but with population denisty sateliite.
- [x]  will calculate total no. of people in radius (this is somewhat arbitrary) but ok for our next step
- [x] *using literatiure* select an appropriate threshhold for AOD to use as a cutoff point for the "high levels of pollution"
- [x] from this calculate total no. of people and % of people in area affected by high levels of pollution

**Comment by ChristinaLast** [comment]
Taking a look at this [research](https://earthobservatory.nasa.gov/global-maps/MODAL2_M_AER_OD) from NASA and [this](https://neo.gsfc.nasa.gov/view.php?datasetId=MODAL2_M_AER_OD) on their AOD dataset

**Comment by ChristinaLast** [comment]
These seem a lot:

- Gwer road: 121183 people
- Kalak: 219058
  - Kawergosk refugee camp 13,646 (source [UNHCR](https://data2.unhcr.org/en/documents/download/41539))
- Lalish: 40925

**Comment by ChristinaLast** [comment]
Taking a look at this articles:
- [What Can Affect AOD–PM2.5 Association?](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2854780/)
- [An empirical relationship between PM2.5 and aerosol optical depth in Delhi Metropolitan](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3237057/)
  - "1% change in AOD explains 0.52±0.202% and 0.39±0.15% change in PM2.5 monitored within ±45 and 150 min intervals of AOD data."
    - [Table with PM2.5 to AOD conversions (for Dehli](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3237057/table/T1/)
      - PM2.5 (μg m−3) 30.5 = AOD (5 km) 172.1

**Comment by ChristinaLast** [comment]
(170.2/30.5 μg/m3 )*5 μg/m3  = 27 μg/m3  [source here](https://www.ersnet.org/wp-content/uploads/2021/10/WHO-AQG_Joint-Society-Statement_1st-UPDATE-13th-October.pdf)

**Comment by ChristinaLast** [comment]
Exposure rates as follow:
- 100% of kalak population above WHO recommended levels of annual mean concentrations of PM2.5
- 100% of gwer road population above WHO recommended levels of annual mean concentrations of PM2.5
- 99.5% of lalish population above WHO recommended levels of annual mean concentrations of PM2.5

**Comment by ChristinaLast** [comment]
Calculating overall average to get figure for no. of times greater than the WHO recommended limit is for each study region, assuming that `(170.2 AOD / 30.5 μg/m3 ) * 5 μg/m3 (WHO limit) = 27 AOD`
- gwer_road = 7.15 x WHO Limit
- Kalak = 7.16 x WHO Limit
- lalish = 7.56 x WHO Limit

​

**Comment by ChristinaLast** [comment]
[Justification for why we are using AOD as a proxy](http://cimss.ssec.wisc.edu/goes/OCLOFactSheetPDFs/ABIQuickGuide_BaselineAerosolOpticalDepth.pdf)

**Comment by ChristinaLast** [comment]
`( 647 / 82.9 μg/m3 )* 5 μg/m3 (WHO limit) = 39.02 AOD
`
