### ISSUE TITLE
Stats on Russian population centres proximity to gas flares versus Iraq (can use study areas) NON-PRIORITY

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#52]
This requires the following:
- [x] Extracting all russian flares
- [x]  Calculating the exposure (e.g. the number of population intersecting areas where there has been flaring over 10x since October 2018).
  - [x] extract `population_density` data for flares in russia active over 10x in the last 3.5 years.
   - [x] extract `population_density` data for flares in iraq active over 10x in the last 3.5 years.
- [x] Calculate no. of `population_density` in flaring locations and derive the following metrics (for Iraq and Russia):
  - [x] total no. of people across all flares
  - [x] no. of people per flare.

**Comment by ChristinaLast** [comment]
What comparison did you actually want to produce? I understand its something about population exposure. Currently I only have population numbers for people in the study regions in iraq, so we either need to:
- find comparable study regions in russia, and sample population from those to compare
- calculate total population exposure in iraq to all flares and do the same for Russia.

The second one will take more time, but is more realistic, Idk what would be considered a "comparable study region" in russia, like we are just making it us at that point. lmk what your thoughts were.

**Comment by ChristinaLast** [comment]
Going for the following:
- calculate total population exposure in iraq to all flares and do the same for Russia.

**Comment by ChristinaLast** [comment]
![iraq_kurdistan_russia_timeseries](https://user-images.githubusercontent.com/36204574/168498923-9c4d7c58-7e4b-4ef1-baf1-de7c936f6411.png)

**Comment by ChristinaLast** [comment]
- This pipeline is built, but will take a long time to run because of the vast scale of Russia. We can reduce this time by:
- reducing the size of the study region, however, this makes it difficult to compare between Iraq and Russia
- Reducing the timeseries. if we only have select dates that we want to compare exposure, rather than over the whole timeperiod, then this will reduce processing time.

In the end we are selecting "active flares" as flares that occured > 10 times since 2018 (not looking at AOD data).

**Comment by ChristinaLast** [comment]
no. of people in russia exposed to > 10 flaring events in study periods (3.5 yrs) = 
274427.8683494413.

**Comment by ChristinaLast** [comment]
no. of people in Iraq exposed to > 10 flaring events in study periods (3.5 yrs) =1190942.7868427187

**Comment by ChristinaLast** [comment]
## Iraq

No. of flares: 2827
no of ppl exposed: 1190942

People per flare: 421.2741422002

## Russia

No. of flares: 4407
no of ppl exposed: 274427

People per flare: 62.2707056955
