### ISSUE TITLE
Get screengrabs from all four video interviews

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#62]
- [x] @ChristinaLast to access photoshop and after affects 
- [x] @ChristinaLast to download relevant videos for stills

**Comment by TomBrown4444** [comment]
![Image](https://user-images.githubusercontent.com/94844764/169589619-df18849f-9a53-4f9e-8fb0-45031e23e052.png)



![Image](https://user-images.githubusercontent.com/94844764/169589626-1e6c5b5c-d88d-4c25-a69c-5aae59661e0f.png)

**Comment by ChristinaLast** [comment]
Shared in this [google folder](https://drive.google.com/drive/folders/17KomBgv16UCmwrUYjwayWIbkWH8mBDH5?usp=sharing)
