### ISSUE TITLE
Map additions:

### ISSUE THREAD

**Issue by TomBrown4444** [ChristinaLast/pollution_analysis_kurdistan#67]
A list of changes to the interactive flaring map of Iraq and Kurdistan:

- [x] - Put the map in dark background
- [x] - Embolden the borders (white outline)
- [x] - Make the city/town names brighter or enlarge them so they can be read more easily
- [x] - Embolden the water ways (get water bodies as a polygon so they stand out better on the map)
- [x] - See if it is possible to add labels pointing out the refugee camp (Kawergosk)
- [x] - [ ] - Make the AOD transparent (so that buildings can be seen behind it etc)

**Comment by ChristinaLast** [comment]
@TomBrown4444 to use [this app](https://demos.mapbox.com/location-helper/) to generate zoom in lat lon values
